#!/bin/bash
# script to make kernels, modules and an update zip for I8000 like phones
# made by Mosci, adapted by Elbee
####

#BetaVersion=2
BetaVersion=3
UpdateFileName=frb${BetaVersion}update

function fix_permissions () {
	Debug=true
	Debug=false
	BaseDir=`pwd`

	# PropertiesFileName defined global
	# PropertiesFilename syntax: <filepropertiesstring> <fileuser> <filegroup> <fullfilename> [-> linktargetfilename]
	# example: lrwxrwxrwx root root system/usr/keychars/s3c-keypad.kcm.bin -> ./qwerty.kcm.bin
	
	cat ${PropertiesFileName} | while true
	do
	  read line
	  if [ $? -ne 0 ]; then exit; fi
	  set -- $line
	  case ${1:0:1} in
	  "d")
	    # Directory entry
	    if [ "${Debug}" = "true" ] ; then echo "($@)"; fi
	    #echo mkdir $4
	    sudo chown $2.$3 $4
	  ;;
	  "l")
	    # Symbolic link entry
	    LinkDir=${4%\/*}/
	    LinkTarget="$6"
	    LinkName=${4##*\/}
	    if [ "${Debug}" = "true" ] ; then echo "($@)"; fi
	    cd ${LinkDir}
	    sudo ln -s ${LinkTarget} ${LinkName}
	    cd ${BaseDir}
	  ;;
	  "-")
	    # File entry
	    UserMod=0; GroupMod=0; OtherMod=0
	    if [ "${1:1:1}" = "r" ] ; then UserMod=`expr $UserMod + 4`; fi
	    if [ "${1:2:1}" = "w" ] ; then UserMod=`expr $UserMod + 2`; fi
	    if [ "${1:3:1}" = "x" ] ; then UserMod=`expr $UserMod + 1`; fi
	    if [ "${1:4:1}" = "r" ] ; then GroupMod=`expr $GroupMod + 4`; fi
	    if [ "${1:5:1}" = "w" ] ; then GroupMod=`expr $GroupMod + 2`; fi
	    if [ "${1:6:1}" = "x" ] ; then GroupMod=`expr $GroupMod + 1`; fi
	    if [ "${1:7:1}" = "r" ] ; then OtherMod=`expr $OtherMod + 4`; fi
	    if [ "${1:8:1}" = "w" ] ; then OtherMod=`expr $OtherMod + 2`; fi
	    if [ "${1:9:1}" = "x" ] ; then OtherMod=`expr $OtherMod + 1`; fi
	    if [ "${Debug}" = "true" ] ; then echo "($@)"; fi
	    sudo chown $2.$3 $4
	    sudo chmod ${UserMod}${GroupMod}${OtherMod} $4
	  ;;
	  "#")
	    # Comment entry
	    if [ "${Debug}" = "true" ] ; then echo "($@)"; fi
	  ;;
	  *)
	    # Unexpected entry
	    if [ "${Debug}" = "true" ] ; then echo "($@)"; fi
	    echo "Error: unexpected line in config file."
	    exit 1
	  ;;
	  esac
	done
}

KERNEL_MODULES_PATH=~/werkdir/omnia2droid/out
if [ ! -d "${KERNEL_MODULES_PATH}" ]
then
	echo -e "\n ${KERNEL_MODULES_PATH} not found!\nplease correct the KERNEL_MODULES_PATH in ${0} !\n";
	exit 1;
fi

# let's try ... see if we have a PHONE_ID and REVISION_ID
if [ $# -eq 2 ] 
then
	case $1 in
	I8000)
		export PHONEMODEL=$1
        	./make_kernel -ckme
		image=zImage
	;;
	B7610)
		export PHONEMODEL=$1
        	./make_kernel -ckme
		image=zImage
	;;
	I920)
		export PHONEMODEL=$1
        	./make_kernel -cume
		image=Image
	;;
	*)
		echo "Phonemodel $1 not supported, try models like I8000, B7610, I920, ..."	
		exit 1;
	;;
	esac

	if [ $? -ne 0 ]
	then
		echo "Making kernel and modules for $1 phone failed!"	
		exit 1;
	fi

	if [ ! -d "./${UpdateFileName}" ]
	then
		echo -e "./${UpdateFileName} not found ... "
		mkdir -m 777 ./${UpdateFileName}
		if [ $? -eq 0 ]
		then
			echo -e "created.\n"
		else
			echo -e "creation failed!"
			exit 1;
		fi
	fi
	
	cd ./${UpdateFileName}/
	
	if [ $? -eq 0 ]
	then
		
		# if local modules-dir not exists ...
		if [ ! -d "./modules" ]
		then
			# ... it will be created
			#mkdir -m 777 ./modules
			mkdir ./modules
			sudo chown root.src ./modules
		else
			# else : remove older version modules (just to get sure)
			sudo rm -f ./modules/*
		fi
		
		# remove older version zImage
		if [ -f ./${image} ]
		then
			rm -f ./${image}
		fi
		
		# remove older version ${UpdateFileName}
		if [ -f ./${UpdateFileName}.tar.gz ]
		then
			rm -f ./${UpdateFileName}.tar.gz
		fi
		
		# copy kernel-modules
		sudo cp ${KERNEL_MODULES_PATH}/*.ko ./modules/
		if [ $?  -gt 0 ]
		then
			 echo -e "\nERROR! no modules found in  ${KERNEL_MODULES_PATH}\n"
			 exit 1;
		else
			 echo "modules copied"
		fi
		sudo chown root.src ./modules/*
		if [ $?  -gt 0 ]
		then
			 echo -e "\nERROR! failed to change root.src ownership to modules\n"
			 exit 1;
		else
			 echo "modules ownership fixed"
		fi
		sudo chmod 644 ./modules/*
		if [ $?  -gt 0 ]
		then
			 echo -e "\nERROR! failed to change rw-r--r-- permissions to modules\n"
			 exit 1;
		else
			 echo "modules permissions fixed"
		fi

		# include other files than ./modules/* in update file
		OLDPATH=`pwd`
		cd ../updates/beta${BetaVersion}/ALL           ; sudo cp -rpf * ${OLDPATH} ; cd ${OLDPATH}
		cd ../updates/beta${BetaVersion}/${PHONEMODEL} ; sudo cp -rpf * ${OLDPATH} ; cd ${OLDPATH}
		sudo find . -type d -name "\.svn" -exec sudo rm -rf {} \;

		# fix permissions and ownership of dirs/files/links
		PropertiesFileName=../updates/beta${BetaVersion}/ALL.prop           ; fix_permissions
		PropertiesFileName=../updates/beta${BetaVersion}/${PHONEMODEL}.prop ; fix_permissions

		# create tar-ball from modules
		tar -czpf ${UpdateFileName}.tar.gz *
		if [ $? -eq 0 ]
		then
			# grant all permissions (just to get sure)
			chmod 777 ${UpdateFileName}.tar.gz
			echo "${UpdateFileName}.tar.gz created"
		else
			echo -e "\nERROR! while creating tar-ball (${UpdateFileName}.tar.gz)\n"
			exit 1;
		fi
		#tar -tvzf ${UpdateFileName}.tar.gz

		# copy kernel
		cp ${KERNEL_MODULES_PATH}/${image} ./
		if [ $? -gt 0 ]
		then
			 echo -e "\nERROR! no ${image} found in  ${KERNEL_MODULES_PATH}\n"
			 exit 1;
		else
			 echo "${image} copied"
		fi
		
		# create zip-file with new (z)Image & new ${UpdateFileName}
		FileName="./Kernel-${1}-${2}.zip"

		OLDPATH=`pwd`
		cd ../updates ; cp -rf changelog.txt ${OLDPATH}       ; cd ${OLDPATH}
		cd ../updates ; cp -rf changelog-${PHONEMODEL}.txt ${OLDPATH} ; cd ${OLDPATH}
		echo "try to create ${FileName} ..."
		zip ${FileName} ./${UpdateFileName}.tar.gz ./${image} ./changelog.txt ./changelog-${PHONEMODEL}.txt
		if [ $? -gt 0 ]
		then
			 echo -e "\nERROR! while creating zip-file ${FileName} of ${UpdateFileName}.tar.gz & ${image}\n"
			 exit 1;
		else
			echo "file: ${FileName} created";
		fi
		
		mv  ${FileName} ../
		if [ $? -eq 0 ]
		then
			cd ../
			echo "file: ${FileName} contains modules (${UpdateFileName}.tar.gz) & ${image}"
		else
			echo -e "\nERROR! - seems that the file ${FileName} is not present (created)\n"
			exit 1;
		fi

 		# remove ./${UpdateFileName} path with contents
		sudo rm -rf ./${UpdateFileName}
	else
		echo "could not change into directory ./${UpdateFileName}";
		exit 1;
	fi
else
 		
 		echo -e "Usage: ${0} <PHONE_ID> <REVISION_ID>\n\nFor example: ${0} I8000 GC-REV6\nFor example: ${0} B7610 PHJ-REV100"
		exit 1; 		
fi
