#!/bin/bash
# script to make kernels, modules and an update zip for I8000 like phones
# made by Mosci, adapted by Elbee
####

KERNEL_MODULES_PATH=~/omnia2droid/svn/trunk/out
if [ ! -d "${KERNEL_MODULES_PATH}" ]
then
	echo -e "\n ${KERNEL_MODULES_PATH} not found!\nplease correct the KERNEL_MODULES_PATH in ${0} !\n";
	exit 1;
fi

# let's try ... see if we have a PHONE_ID and REVISION_ID
if [ $# -eq 2 ] 
then
	export PHONEMODEL=$1
        ./make_kernel -ckme

	if [ $? -ne 0 ]
	then
		echo "Making kernel and modules for $1 phone failed!"	
		exit 1;
	fi

	if [ ! -d "./o2b2update" ]
	then
		echo -e "./o2b2update not found ... "
		mkdir -m 777 ./o2b2update
		if [ $? -eq 0 ]
		then
			echo -e "created.\n"
		else
			echo -e "creation failed!"
			exit 1;
		fi
	fi
	
	cd ./o2b2update/
	
	if [ $? -eq 0 ]
	then
		
		# if local modules-dir not exists ...
		if [ ! -d "./modules" ]
		then
			# ... it will be created
			mkdir -m 777 ./modules
		else
			# else : remove older version modules (just to get sure)
			rm -f ./modules/*
		fi
		
		# remove older version zImage
		if [ -f ./zImage ]
		then
			rm -f ./zImage
		fi
		
		# remove older version o2b2update
		if [ -f ./o2b2update.tar.gz ]
		then
			rm -f ./o2b2update.tar.gz
		fi
		
		# copy kernel-modules
		cp ${KERNEL_MODULES_PATH}/*.ko ./modules/
		if [ $?  -gt 0 ]
		then
			 echo -e "\nERROR! no modules found in  ${KERNEL_MODULES_PATH}\n"
			 exit 1;
		else
			 echo "modules copied"
		fi
		
		# copy kernel
		cp ${KERNEL_MODULES_PATH}/zImage ./
		if [ $? -gt 0 ]
		then
			 echo -e "\nERROR! no zImage found in  ${KERNEL_MODULES_PATH}\n"
			 exit 1;
		else
			 echo "zImage copied"
		fi
		
		# create tar-ball from modules
		tar -czpf o2b2update.tar.gz ./modules
		if [ $? -eq 0 ]
		then
			# grant all permissions (just to get sure)
			chmod 777 o2b2update.tar.gz
			 echo "o2b2update.tar.gz created"
		else
			echo -e "\nERROR! while creating tar-ball (o2b2update.tar.gz)\n"
			exit 1;
		fi

		# create zip-file with new zImage & new o2b2update
		FileName="./Kernel-${1}-${2}.zip"

		echo "try to create ${FileName} ..."
		zip ${FileName} ./o2b2update.tar.gz ./zImage
		if [ $? -gt 0 ]
		then
			 echo -e "\nERROR! while creating zip-file ${FileName} of o2b2update.tar.gz & zImage\n"
			 exit 1;
		else
			echo "file: ${FileName} created";
		fi
		
		mv  ${FileName} ../
		if [ $? -eq 0 ]
		then
			cd ../
			echo "file: ${FileName} contains modules (o2b2update.tar.gz) & zImage"
			exit 0;
		else
			echo -e "\nERROR! - seems that the file ${FileName} is not present (created)\n"
			exit 1;
		fi

 		# remove ./o2b2update path with contents
		cd ..
		rm -rf ./o2b2update/
	else
		echo "could not change into directory ./o2b2update";
		exit 1;
	fi
else
 		
 		echo -e "Usage: ${0} <PHONE_ID> <REVISION_ID>\n\nFor example: ${0} I8000 GC-REV6\nFor example: ${0} B7610 PHJ-REV100"
		exit 1; 		
fi
